config/routes.rb
Rails.application.routes.draw do
  resources :get_commits
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/get_commit.rb
class GetCommit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/get_commits_controller.rb
class GetCommitsController < ApplicationController
  before_action :set_get_commit, only: %i[ show edit update destroy ]

  # GET /get_commits or /get_commits.json
  def index
    @get_commits = GetCommit.all
  end

  # GET /get_commits/1 or /get_commits/1.json
  def show
  end

  # GET /get_commits/new
  def new
    @get_commit = GetCommit.new
  end

  # GET /get_commits/1/edit
  def edit
  end

  # POST /get_commits or /get_commits.json
  def create
    @get_commit = GetCommit.new(get_commit_params)

    respond_to do |format|
      if @get_commit.save
        format.html { redirect_to @get_commit, notice: "Get commit was successfully created." }
        format.json { render :show, status: :created, location: @get_commit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @get_commit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /get_commits/1 or /get_commits/1.json
  def update
    respond_to do |format|
      if @get_commit.update(get_commit_params)
        format.html { redirect_to @get_commit, notice: "Get commit was successfully updated." }
        format.json { render :show, status: :ok, location: @get_commit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @get_commit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /get_commits/1 or /get_commits/1.json
  def destroy
    @get_commit.destroy
    respond_to do |format|
      format.html { redirect_to get_commits_url, notice: "Get commit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_get_commit
      @get_commit = GetCommit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def get_commit_params
      params.fetch(:get_commit, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/get_commits_helper.rb
module GetCommitsHelper
end

app/views/get_commits/_form.html.erb
<%= form_with(model: get_commit) do |form| %>
  <% if get_commit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(get_commit.errors.count, "error") %> prohibited this get_commit from being saved:</h2>

      <ul>
        <% get_commit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/get_commits/edit.html.erb
<h1>Editing Get Commit</h1>

<%= render 'form', get_commit: @get_commit %>

<%= link_to 'Show', @get_commit %> |
<%= link_to 'Back', get_commits_path %>

app/views/get_commits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Get Commits</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @get_commits.each do |get_commit| %>
      <tr>
        <td><%= link_to 'Show', get_commit %></td>
        <td><%= link_to 'Edit', edit_get_commit_path(get_commit) %></td>
        <td><%= link_to 'Destroy', get_commit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Get Commit', new_get_commit_path %>

app/views/get_commits/new.html.erb
<h1>New Get Commit</h1>

<%= render 'form', get_commit: @get_commit %>

<%= link_to 'Back', get_commits_path %>

app/views/get_commits/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_get_commit_path(@get_commit) %> |
<%= link_to 'Back', get_commits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>